### ISSUE TITLE
Start NetworkManager by default on startup

### ISSUE THREAD

**Issue by linux-leo** [chimera-linux/dinit-chimera#2]
Just installed this in a VM and noticed this..
![Screenshot_linux2020_2022-06-21_19:44:38](https://user-images.githubusercontent.com/63003858/174864937-8808048c-074c-49c8-9a17-f021da8d1366.png)
.

**Comment by q66** [comment]
`dinitctl enable networkmanager`

**Comment by q66** [comment]
the service system will go through a lot of refactoring before i declare anything as stable, but it should technically only get simpler from the current state (but there will be breaking changes)
