### ISSUE TITLE
Shutdown hangs on "stopping remainging crypto disks"

### ISSUE THREAD

**Issue by Jimbassfisher** [chimera-linux/dinit-chimera#5]
I have two drives in an x86_64 pc, both encrypted with luks2. One is my root, and the other is a second drive mounted on /mnt/extra mounted through fstab, and decrypted with a keyfile specified in crypttab.

Whenever I reboot or shutdown, my pc hangs on "stopping remainging crypto disks". However, if I ummount and luksClose the drive mounted on /mnt/extra, my pc shutsdown properly.

**Comment by q66** [comment]
what if you only umount?

**Comment by Jimbassfisher** [comment]
If I only issue umount and don't close the drive, it also hangs at "stopping remainging crypto disks"

**Comment by q66** [comment]
is there any LVM or something else on the LUKS? or just a basic filesystem?

**Comment by Jimbassfisher** [comment]
There are no LVM's, just a btrfs filesystem mounted as a subvolume with the name @extra

**Comment by q66** [comment]
can you test modifying /usr/lib/cryptsetup/cryptdisks-functions by commenting out the `dmsetup mknodes` in `do_stop`?

**Comment by q66** [comment]
there is also this patch that i want you to try https://github.com/chimera-linux/dinit-chimera/commit/ed94cacc386c341aa4edb7954496b336d42c02e3 (without `dmsetup mknodes` commented out)

**Comment by q66** [comment]
alright, fixed then

I'll pull it into packages
